### PR TITLE
Moved the string cache to a separate file

### PR DESCRIPTION
**Pull request by vintagedave**
Some minor changes:
 - Fix for XE8 / Seattle's ToArray
 - Moved the string cache from DelphiAST.Classes to its own file. This file sits in SimpleParser, which means no SimpleParser code depends on DelphiAST code, only the other way around.

### CODE REVIEW

**Comment by RomanYankovsky** [comment]
> This branch has conflicts that must be resolved

Do you have an idea what's wrong with it?

**Comment by vintagedave** [comment]
I have absolutely no idea :/  Definitely in arcane git territory now.

All I did was continue in my private fork - the one I worked from
originally - and made some more changes.

**Comment by RomanYankovsky** [comment]
I did some changes in my branch too. Perhaps that's why there is a conflict. I'll try to figure out this tomorrow. Anyways, changes look good, we just need to make guthub merge them :)

**Comment by RomanYankovsky** [comment]
Sorry, still didn't have a chance. Looking forward to merge this later next week.

**Comment by sglienke** [comment]
Usually you always want to rebase the fork branch on origin branch (need to force push your fork after that, pull request will update automatically) so you have the latest changes that happened to the origin. That will always result in a mergeable pull request.

**Comment by RomanYankovsky** [comment]
@sglienke how can I enforce this merge rewriting everything? It will be easier for me to repeat my changes manually then.

**Comment by sglienke** [comment]
My comment was to David as he should fix that in his fork. just my 2cc

**Comment by vintagedave** [comment]
Thanks @sglienke. It still had conflicts; I reimplemented in a new fork, rebased (you might have seen that pull request?) and have been using that technique since.

**Pull request closed without merging**
