### PR TITLE
Hints & Warnings fixed, other Default Defines supported

### PR DESCRIPTION
**Pull request by LaKraven**
as the title says

### CODE REVIEW

**Comment by sglienke** [comment]
The code will break again for the next Delphi version if you use defines like this.
It's completely unnecessary to generate this future maintenance need.

Personally I dislike commenting almost every changed line with your tag. Isn't that what VCS is for?

As for putting yourself at the first spot in the contributor list... well...

**Comment by LaKraven** [comment]
@sglienke I've simply added defines in the same manner as those already defined... had I changed the original convention, you'd be whining about that instead.

Personally, I don't care whether you dislike the commenting of every changed line. That's what others have done, and had I not I'm sure you'd be whining about that too.

As for putting myself first, I merely did what Roman did and prepended the entry. Personally I don't care where it goes in the list, and your attitude is as distasteful as the unwarranted inferences you insist on making.

I ask that you do not converse with me again, comment on anything I post, or in any way interact with me in the future as your attitude is unnecessary and offensive.

**Comment by LaKraven** [comment]
@RomanYankovsky I apologize for that... I forgot to remove the commented lines after I had tested that their removal did not in fact break any functionality. That was a simple post-mortem housekeeping failure on my part, and I'll make sure to remove them entirely in the future (as I do with my own repositories)

**Comment by LaKraven** [comment]
@RomanYankovsky would you like me to remove these commented lines and submit a fresh pull request?

**Comment by RomanYankovsky** [comment]
@LaKraven Yes, please. This would be great.

**Pull request closed without merging**
