### PR TITLE
AST binary (de)serialization

### PR DESCRIPTION
**Pull request by gabr42**
Hi there!

I wrote a class that serializes AST to a stream and deserializes it back.

Also modified: added TSyntaxTreeWriter.ToBinary which forwards request to the binary serializer.

Currently the code probably works only in Delphi as it uses a TDictinary<>. Other than that there should be no FPC incompatibilities.

### CODE REVIEW

**Comment by RomanYankovsky** [comment]
Very interesting. I just wonder, what do you use this for? What's your application of DelphiAST?

**Comment by gabr42** [comment]
I started work on a project indexer and indexing 10000 units every time you need some information is a bit sloooow ... The rest is, for the moment, confidential :) (although, with some luck, everything will be open sourced when half ready).

OTOH, I found out that I won't need this serialization directly after I wrote serializer ;) but I still decided to complete the work (deserializer) and make my contribution to the project.

**Comment by gabr42** [comment]
Moved DelphiAST.Serialize.Binary to the Source folder ...

**Comment by Wosi** [comment]
Nice, I'll have a look at it when I find the time. 

> Currently the code probably works only in Delphi as it uses a TDictinary<>. Other than that there should be no FPC incompatibilities.

The FPC version of Generics.Collections is already a submodule in this repository. There should only be two small things to change in your code for FPC support

1. Add `{$IFDEF FPC}{$MODE DELPHI}{$ENDIF}` to the top of the new units.
2. Replace `System.Generics.Collections` with `Generics.Collections` in the uses sections.

**Comment by RomanYankovsky** [comment]
Thanks!

**Comment by gabr42** [comment]
Closed but not merged?

**Comment by RomanYankovsky** [comment]
Sorry, my bad :)

**Pull request merged**
