### PR TITLE
Fix #84: Add support for strict private/protected

### LINKED ISSUE #84: Add support for strict private/protected
The visibility modifier <code>strict</code> is not reflected in the syntax tree.

### PR DESCRIPTION
**Pull request by Wosi**
Referring to https://github.com/RomanYankovsky/DelphiAST/issues/84
Is there any reason why @JBontes solution has it never been made into `master`?
I added support for `strict private` and `strict protected` on my own now. The approach is slightly different compared to @JBontes solution: 
I don't add a `visibility` attribute to the `ntPrivate` and `ntProtected` nodes in order to represent the `strict` keyword. I introduce the new node types `ntStrictPrivate` and `ntStrictProteced`. It's in my opinion the cleaner way than adding some string values or flags to the existing nodes. But I can change it if you don't like it.

This is a breaking change as `strict private` and `strict protected` members are no longer located inside the `ntPrivate` and `ntProtected` nodes.

### CODE REVIEW

**Comment by RomanYankovsky** [comment]
> Is there any reason why @JBontes solution has it never been made into master?

@JBontes did good thinks, I'm really sorry I didn't merge that. There were two reasons. I didn't want to add parameters to TPasSyntaxTreeBuilder methods like: 

```delphi
procedure TPasSyntaxTreeBuilder.VisibilityPrivate(IsStrict: boolean = false);
```

I just want to keep parser's code consistent.

The second reason is that his pull request has some conflicts with other changes.

And the third reason is that I was too busy to disccuss this issue. My fault. I really appreciate his work.

**Comment by RomanYankovsky** [comment]
> It's in my opinion the cleaner way than adding some string values or flags to the existing nodes. But I can change it if you don't like it.

This makes the tree more difficult to analyze. In most cases you don't care if a section's visibility strict or not. My vote for adding "string" as node parameter. But let's see what other's think.

**Comment by RomanYankovsky** [comment]
I've been told that there is an option to use rebase command to get rid of commits like "Added constref keyword" and then "Revert "Added constref keyword"" to make commit history more compact. I'm not a github guru, everything I know is that the keywords are "interactive rebase" and "squash".

**Comment by Wosi** [comment]
Thanks for the info. I'm not a git pro yet, sorry. I'll use rebase in case this is going to be pulled. 

> This makes the tree more difficult to analyze. In most cases you don't care if a section's visibility strict or not. 

I think it's the opposite. I see two general cases to use DelphiAST:
  - In case 1 you completely don't care about visibility (e.g. Parnassus Navigator)
  - In case 2 you want to know exactly about visibility. Ignoring the `strict` keyword will sooner or later lead to a bug ticket.

In case 1 you already have to deal with `ntPrivate`, `ntProtected` etc. 
In case 2 (my case) you can have methods like this:

```delphi
function GetSymbolNodes(ClassNode: TSyntaxNode; VisibilityNodeTypes: TSyntaxNodeTypeSet): IList<TSyntaxNode>;
begin
  // iterate over all ChildNodes where Typ in VisibilityNodeTypes and add their ChildNodes to Result
end;

function GetPrivateSymbolNodes(ClassNode: TSyntaxNode): IList<TSyntaxNode>;
begin
  Result := GetSymbolNodes(ClassNode, [ntPrivate]);
end;

function GetStrictPrivateSymbolNodes(ClassNode: TSyntaxNode): IList<TSyntaxNode>;
begin
  Result := GetSymbolNodes(ClassNode, [ntStrictPrivate]);
end;

// ...
function GetPublicSymbolNodes(ClassNode: TSyntaxNode): IList<TSyntaxNode>;
begin
  Result := GetSymbolNodes(ClassNode, [ntPublic]);
end;

function GetAllSymbolNodes(ClassNode: TSyntaxNode): IList<TSyntaxNode>;
begin
  Result := GetSymbolNodes(ClassNode, [ntPrivate, ntStrictPrivate, ntProtected, ntStrictProtected, ntPublic, ntPublished]);
end;
```
The way to extract symbols of different visibilities looks clean to me. Cleaner then carrying an `IsStrict` flag around which is only applicable to `ntPrivate` and `ntProtected`.

But as I said before it's my personal taste. I'll change it in case you don't aggree with this approach.

**Comment by sglienke** [comment]
I think Roman meant you should clean up your repository before this is going to be pulled. The changes are not much so this entire change firs into one single commit.

To do this I suggest you do a soft reset (in order to keep your changes) of your repository to the main head and commit your changes. Then do a force push (to override your currently messed up remote) which will update this merge request automatically.

**Comment by RomanYankovsky** [comment]
OK, as far as I understood nobody disagree, so I will merge this. Personally for me it's not very important, so I'm OK with the way you did it.

**Comment by Wosi** [comment]
OK, I'm going to clean the commits as soon as possible.

**Comment by Wosi** [comment]
Thanks to @sglienke and this helpful answer http://stackoverflow.com/questions/6102297/how-do-i-clean-up-my-github-fork-so-i-can-make-clean-pull-requests
The change log is cleaned up.

**Comment by JBontes** [comment]
Good to see the feature made it.

**Pull request merged**
